//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wood_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public string Name_product { get; set; }
        public Nullable<int> Quentity { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_product { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual user user { get; set; }
    }
}
